flags: {}
extra-package-dbs: []
templates:
  params:
    author-email: stgallag@gmail.com
    copyright: Copyright (C) 2016 Sean Gallagher
    category: Text, NLP
    github-username: SeanTater
    author-name: Sean Gallagher
packages:
- '.'
extra-deps:
- base-orphans-0.5.4
- mono-traversable-0.10.2
- text-1.2.2.1
- unordered-containers-0.2.7.0
- lz4-0.2.3.1
resolver: lts-5.12
