flags: {}
extra-package-dbs: []
templates:
  params:
    author-email: stgallag@gmail.com
    copyright: Copyright (C) 2016 Sean Gallagher
    category: Text, NLP
    github-username: SeanTater
    author-name: Sean Gallagher
packages:
- '.'
- 'haskell-eigen'
extra-deps:
- lz4-0.2.3.1
- text-1.2.2.1
- eigen-2.1.6
resolver: lts-6.2
