flags: {}
extra-package-dbs: []
templates:
  params:
    author-email: stgallag@gmail.com
    copyright: Copyright (C) 2016 Sean Gallagher
    category: Text, NLP
    github-username: SeanTater
    author-name: Sean Gallagher
packages:
- '.'
#- 'hmatrix-svdlibc'
extra-deps:
# - lz4-0.2.3.1
#- text-1.2.2.1
#- storable-tuple-0.0.3.2
#- storable-record-0.0.3.1
- hmatrix-svdlibc-0.4.0
resolver: lts-6.9
